application:
  authentication:
    access_token:
      jwt_secret: "Z8GJ64eimY"
      life_time: "3600000"
    refresh_token:
      jwt_secret: "Z8GJ64eimY"
      life_time: "3600000"

  i18n:
    resources:
      - classpath:core-authentication/message
      - classpath:tdl-core/message

spring:
  application:
    name: tdl-service

  liquibase:
    changelog: classpath:/database.migration/master-changelog.xml
  datasource:
    url: jdbc:mysql://localhost:3306/tdl
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379


  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
