application:
  authentication:
    access_token:
      jwt_secret: "Z8GJ64eimY"
      life_time: "3600000"

  i18n:
    resources:


spring:
  application:
    name: tdl-service

  liquibase:
    changelog: classpath:/database.migration/master-changelog.xml
    datasource:
      url: jdbc:mysql://localhost:3307/tdl
      username:
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379